name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    if: github.event.pull_request.user.login != 'ches3-bot[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Test
        run: bun run test
